name: 📊 SonarQube

on:
  workflow_call:
    inputs:
      has-js-coverage:
        description: "Whether JS coverage is available"
        type: boolean
        default: false
      has-php-coverage:
        description: "Whether PHP coverage is available"
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        required: false

jobs:
  scan:
    name: 📊 SonarQube
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Restore JS coverage
        if: inputs.has-js-coverage
        uses: actions/cache/restore@v5
        with:
          path: coverage/js/lcov.info
          key: coverage-js-${{ github.ref_name }}

      - name: Restore PHP coverage
        if: inputs.has-php-coverage
        uses: actions/cache/restore@v5
        with:
          path: coverage/php/coverage.xml
          key: coverage-php-${{ github.ref_name }}

      - name: Scan with SonarQube
        uses: sonarsource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ secrets.SONAR_TOKEN != '' }}
